import { Response } from 'express';
import { AuthenticatedRequest } from '../middlewares/middleware';
import { S3Client, PutObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { getIO } from '../socketServer';
import { RATE_LIMIT_CONFIG } from '../middlewares/rateLimiter';
import Summary from '../models/Summary';
import { generateEmbedding } from './AiController';
import { getUploadCount, incrementUploadCount } from '../db/queries/uploadCounters';

// ── Lazy-initialized R2 client ──────────────────────────────────
let _s3: S3Client | null = null;

function getR2Client(): S3Client {
  if (!_s3) {
    const accountId = process.env.R2_ACCOUNT_ID || '';
    _s3 = new S3Client({
      region: 'auto',
      endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
      credentials: {
        accessKeyId: process.env.R2_ACCESS_KEY_ID || '',
        secretAccessKey: process.env.R2_SECRET_ACCESS_KEY || '',
      },
    });
  }
  return _s3;
}

function getBucket(): string {
  return process.env.R2_BUCKET_NAME || 'study-summaries';
}

// ── Build a styled HTML document from the summary ───────────────
function buildSummaryHTML(summary: string, userName: string, roomId: string): string {
  const date = new Date().toLocaleString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  // Convert markdown-style bullet points to HTML list items
  const lines = summary.split('\n').filter((l) => l.trim());
  const bodyHTML = lines
    .map((line) => {
      const trimmed = line.replace(/^[-•*]\s*/, '').trim();
      if (line.match(/^[-•*]\s/)) return `<li>${trimmed}</li>`;
      if (line.match(/^\*\*/)) return `<h3>${trimmed.replace(/\*\*/g, '')}</h3>`;
      return `<p>${trimmed}</p>`;
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Study Session Summary — ${date}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
      background: #f8f9fc;
      color: #1e293b;
      padding: 2rem;
      line-height: 1.7;
    }
    .container {
      max-width: 720px;
      margin: 0 auto;
      background: #fff;
      border-radius: 16px;
      box-shadow: 0 4px 24px rgba(0,0,0,0.06);
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);
      color: #fff;
      padding: 2rem 2.5rem;
    }
    .header h1 { font-size: 1.5rem; font-weight: 700; margin-bottom: 0.5rem; }
    .header .meta { font-size: 0.85rem; opacity: 0.85; }
    .header .meta span { margin-right: 1.5rem; }
    .body { padding: 2rem 2.5rem; }
    .body h3 {
      font-size: 1rem;
      font-weight: 700;
      color: #6366f1;
      margin: 1.5rem 0 0.5rem;
    }
    .body ul { padding-left: 1.25rem; margin: 0.5rem 0; }
    .body li {
      margin-bottom: 0.5rem;
      font-size: 0.95rem;
    }
    .body p { margin-bottom: 0.75rem; font-size: 0.95rem; }
    .footer {
      border-top: 1px solid #e5e7eb;
      padding: 1.25rem 2.5rem;
      text-align: center;
      font-size: 0.75rem;
      color: #94a3b8;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>Study Session Summary</h1>
      <div class="meta">
        <span>By ${userName}</span>
        <span>Room: ${roomId}</span>
        <span>${date}</span>
      </div>
    </div>
    <div class="body">
      <ul>
        ${bodyHTML}
      </ul>
    </div>
    <div class="footer">
      Generated by Virtual Study Group AI
    </div>
  </div>
</body>
</html>`;
}

// ── Save summary to R2 + MongoDB ────────────────────────────────
export const saveSummary = async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  try {
    const {
      summary,
      roomId,
      type = 'room',
      contextId,
      contextLabel = '',
      title,
    } = req.body as {
      summary: string;
      roomId: string;
      type?: 'room' | 'dm' | 'whiteboard';
      contextId?: string;
      contextLabel?: string;
      title?: string;
    };
    const userName = req.user?.name || 'Unknown';
    const userId = req.user?.userId || 'unknown';

    if (!summary || summary.trim().length === 0) {
      res.status(400).json({ error: 'Summary content is required' });
      return;
    }

    // ── Monthly upload limit check ──────────────────────────────
    const now = new Date();
    const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
    const maxUploads = RATE_LIMIT_CONFIG.R2_MAX_UPLOADS_PER_MONTH;

    const currentCount = await getUploadCount(userId, monthKey);
    if (currentCount >= maxUploads) {
      res.status(429).json({
        error: `Monthly upload limit reached (${maxUploads}). Resets next month.`,
      });
      return;
    }

    const resolvedContextId = contextId || roomId;
    const timestamp = Date.now();
    const key = `summaries/${userId}/${resolvedContextId}_${timestamp}.html`;
    const html = buildSummaryHTML(summary, userName, resolvedContextId);

    await getR2Client().send(
      new PutObjectCommand({
        Bucket: getBucket(),
        Key: key,
        Body: html,
        ContentType: 'text/html',
      })
    );

    // ── Increment monthly upload counter ──────────────────────────
    await incrementUploadCount(userId, monthKey);

    // Generate a presigned download URL (valid 7 days)
    const downloadUrl = await getSignedUrl(
      getR2Client(),
      new GetObjectCommand({ Bucket: getBucket(), Key: key }),
      { expiresIn: 7 * 24 * 60 * 60 }
    );

    // ── Generate embedding for RAG search ──────────────────────
    const resolvedTitle = title || `${({ room: 'Room Chat', dm: 'DM', whiteboard: 'Whiteboard' } as const)[type]} Summary`;
    let embedding: number[] = [];
    try {
      embedding = await generateEmbedding(`${resolvedTitle} ${summary}`);
    } catch (err: any) {
      console.warn('Embedding generation failed, saving without:', err?.message);
    }

    // ── Persist to MongoDB ──────────────────────────────────────
    const dateStr = now.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    const typeLabels = { room: 'Room Chat', dm: 'DM', whiteboard: 'Whiteboard' };
    await Summary.create({
      userId,
      type,
      contextId: resolvedContextId,
      contextLabel,
      title: title || `${typeLabels[type]} Summary - ${dateStr}`,
      content: summary,
      r2Key: key,
      r2Url: downloadUrl,
      embedding,
    });

    // Broadcast the summary link to the room chat as a VSG Bot message
    const io = getIO();
    if (io && roomId && type !== 'dm') {
      io.to(roomId).emit(`message:${roomId}`, {
        msg: `📄 ${userName} saved a session summary! View it here: ${downloadUrl}`,
        sentby: 'bot',
      });
    }

    res.status(200).json({ url: downloadUrl, key });
  } catch (error: any) {
    console.error('R2 upload error:', error?.message);
    res.status(500).json({ error: 'Failed to save summary. Please try again.' });
  }
};

// ── List user's summaries ───────────────────────────────────────
export const listSummaries = async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  try {
    const userId = req.user?.userId;
    const { type } = req.query as { type?: string };

    const filter: any = { userId };
    if (type && ['room', 'dm', 'whiteboard'].includes(type)) {
      filter.type = type;
    }

    const summaries = await Summary.find(filter)
      .sort({ createdAt: -1 })
      .limit(50)
      .select('type contextId contextLabel title content r2Key createdAt');

    res.status(200).json({ summaries });
  } catch (error: any) {
    console.error('List summaries error:', error?.message);
    res.status(500).json({ error: 'Failed to fetch summaries.' });
  }
};

// ── Download a summary (fresh presigned URL) ──────────────────
export const downloadSummary = async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  try {
    const userId = req.user?.userId;
    const { id } = req.params;

    const doc = await Summary.findOne({ _id: id, userId }).select('r2Key');
    if (!doc?.r2Key) {
      res.status(404).json({ error: 'Summary not found or no file available' });
      return;
    }

    const url = await getSignedUrl(
      getR2Client(),
      new GetObjectCommand({ Bucket: getBucket(), Key: doc.r2Key }),
      { expiresIn: 3600 }
    );

    res.status(200).json({ url });
  } catch (error: any) {
    console.error('Download summary error:', error?.message);
    res.status(500).json({ error: 'Failed to generate download link.' });
  }
};

// ── Delete a summary ────────────────────────────────────────────
export const deleteSummary = async (req: AuthenticatedRequest, res: Response): Promise<void> => {
  try {
    const userId = req.user?.userId;
    const { id } = req.params;

    const doc = await Summary.findOneAndDelete({ _id: id, userId });
    if (!doc) {
      res.status(404).json({ error: 'Summary not found' });
      return;
    }

    res.status(200).json({ success: true });
  } catch (error: any) {
    console.error('Delete summary error:', error?.message);
    res.status(500).json({ error: 'Failed to delete summary.' });
  }
};
